on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Publish
        run: |
          C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm rsync; which rsync"
          echo "##[add-path]C:\msys64\usr\bin"
          dotnet publish Chatterbox.sln --configuration Release --output build
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          branch: build
          folder: build
          single-commit: true