on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Publish
        run: dotnet publish $PROJECT_PATH --configuration Release --output build
        env:
          PROJECT_PATH: Chatterbox.sln # change this to match your solution
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          branch: build
          folder: build
          single-commit: true