# this workflow built for...
# < Building .NET Applications >
#
# checkout my other workflow templates @ https://github.com/dentolos19/ActionsPlayground
#
# created by Dennise Catolos (https://github.com/dentolos19)

name: Build .NET
on: # change this when using this in a project
  push:
    paths:
      - Chatterbox/**
      - Chatterbox.Core/**
      - Chatterbox.Server/**
  workflow_dispatch:
concurrency:
  group: release
  cancel-in-progress: true

env: # change these settings when using this in a project
  TARGET_BRANCH: ${{ github.event.repository.default_branch }}
  DOTNET_VERSION: 6.0.x
  PROJECT_FILE: Chatterbox.sln
  SELF_CONTAINED: false
  ARTIFACT_NAME: Output
  RELEASE_TAG: Canary

jobs:
  build:
    continue-on-error: true
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TARGET_BRANCH }}
          submodules: recursive
          lfs: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Publish Project
        run: |
          dotnet publish ${{ env.PROJECT_FILE }} -c Release -o build --sc ${{ env.SELF_CONTAINED }}
          $artifacts = (Get-ChildItem build/*).FullName
          New-Item -ItemType Directory artifacts
          Compress-Archive $artifacts artifacts/${{ github.event.repository.name }}.zip
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: artifacts
  release:
    needs: build
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: artifacts
      - id: artifacts
        name: Check Artifacts
        run: |
          $artifacts = (Get-ChildItem -Recurse -File artifacts).FullName
          $artifactList = ""
          foreach ($artifact in $artifacts) {
            if ($artifactList.Length -gt 0) {
              $artifactList += ","
            }
            $artifactList += $artifact
          }
          Write-Output "::set-output name=RELEASE_ARTIFACTS::$artifactList"
      - name: Delete (Existing) Release Tag
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
      - name: Release Artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.artifacts.outputs.RELEASE_ARTIFACTS }}
          prerelease: true
          tag: ${{ env.RELEASE_TAG }}
          commit: ${{ env.TARGET_BRANCH }}